baseURL = "https://glittery-bunny-1035bc.netlify.app"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Portfolio Léo LUCAS"
theme = "naturaliste"

[params]
  author = "Léo LUCAS"
  description = "Portfolio naturaliste — Observations de la faune et de la flore"
  tagline = "Carnet de terrain"

[markup.goldmark.renderer]
  unsafe = true
